=== KamilTalowski/SpringBasics/SpringBoot/XMLDemo/src/AlienSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/AlienSchema"
	xmlns:tns="http://www.example.org/AlienSchema"
	elementFormDefault="qualified">

	<complexType name="alienstype">
		<sequence>
			<element name="alien" type="tns:alientype" maxOccurs="3" />
		</sequence>
	</complexType>

	<complexType name="alientype">
		<sequence>
			<element name="name" type="string" />

			<element name="salary" type="tns:mySal" />
		</sequence>
		<attribute name="aid" type="ID" use="required" />

	</complexType>
	<element name="globalaliens" type="tns:alienstype" />
	<simpleType name="mySal">
		<restriction base="integer">
			<minInclusive value="1000"></minInclusive>
			<maxInclusive value="10000"></maxInclusive>
		</restriction>
	</simpleType>
</schema>

=== KamilTalowski/SpringBasics/SpringBoot/XMLDemo/src/newAliens.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalaliens xmlns:tns="http://www.example.org/AlienSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/AlienSchema AlienSchema.xsd ">
  <tns:alien aid="A1">
    <tns:name>Kamil</tns:name>
    <tns:salary>10000</tns:salary>
  </tns:alien>
  <tns:alien aid="A2">
    <tns:name>Krystian</tns:name>
    <tns:salary>10000</tns:salary>
  </tns:alien>
  <tns:alien aid="A3">
    <tns:name>Kuba</tns:name>
    <tns:salary>3000</tns:salary>
  </tns:alien>
</tns:globalaliens>
